ProjectGhost/Pages/AddUser.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace ProjectGhost.Pages
{
    public class AddUserModel : PageModel
    {
        
        public List<string> GhostNames = new List<string>();
        public bool firstAttemptFail;

        public void OnGet()
        {
            // get all the ghost names from db
            GhostNames = Program.Manager.ReturnGhostNames();
        }

        public void OnPostCreateAccount(string email, string password, string serialNum, string ghostName)
        {

            string newSerial = serialNum.ToUpper();
            string pattern = "[0-9][0-9][A-Z][A-Z][0-9][0-9]AD";

            Regex regex = new Regex(pattern);
            Match isMatch = regex.Match(newSerial);

            GhostNames.Clear();
            Program.Manager.GhostNames.Clear();

            if (isMatch.Success)
            {
                firstAttemptFail = false;
                Program.Manager.CreateAccount(email, password, newSerial, ghostName);
                Response.Redirect("./Index");
                
            }
            else
            {
                firstAttemptFail = true;
                //alert if cereal has no milk
            }

        }
    }
}

ProjectGhost/Pages/Admin.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace ProjectGhost.Pages
{
    public class AdminModel : PageModel
    {
        public string[] timeOfDay = {"12:00", "12:15", "12:30", "12:45", "1:00", "1:15", "1:30", "1:45", "2:00", "2:15", "2:30", "2:45", "3:00",
            "3:15", "3:30", "3:45", "4:00", "4:15", "4:30", "4:45", "5:00", "5:15", "5:30", "5:45", "6:00", "6:15", "6:30", "6:45",
            "7:00", "7:15", "7:30", "7:45", "8:00", "8:15", "8:30", "8:45", "9:00", "9:15", "9:30", "9:45", "10:00", "10:15", "10:30",
            "10:45", "11:00", "11:15", "11:30", "11:45"
        };

        public int ScheduleID;
        public int Day = Program.Manager.Day;
        public int On = Program.Manager.On;
        public int Off = Program.Manager.Off;
        public int capType = Program.Manager.capType;
        public int recDur = Program.Manager.recDur;
        public int recDel = Program.Manager.recDel;
        public int snapDel = Program.Manager.snapDel;


        public int OptionsID;
        public int Brightness = Program.Manager.Brightness;
        public int Contrast = Program.Manager.Contrast;
        public int Led = Program.Manager.Led;
        public int Volume = Program.Manager.Volume;
        public int Mic = Program.Manager.Microphone;
        public int Prox = Program.Manager.Proximity;
        public int Audio = Program.Manager.Audio;


        public void OnGet()
        {
            var UserID = Program.Manager.UserID;
            var GhostID = Program.Manager.GhostID;
            var ScheduleID = Program.Manager.ScheduleID;
            ReloadOptions();
        }

        public void OnPostMiscOptions(int brightness, int contrast, int ledToggle, int volume,
                                   int micToggle, int proximityToggle, int audioToggle)
        {
            // uses Gpio Pin 17
            //Program.Connections.LedToggle(ledToggle);

            
            // Adds all the options to DB
            Program.Manager.AddOptions(brightness, contrast, volume, ledToggle, micToggle, proximityToggle, audioToggle);

            // Changes the camera Options on the PI
            //Program.Connections.Send_cmd("br", brightness);
            //Program.Connections.Send_cmd("co", contrast);

            ReloadOptions();
        }

        public void ReloadOptions()
        {
            Program.Manager.ReturnLastOptions();
            OptionsID = Program.Manager.OptionsID;
            Brightness = Program.Manager.Brightness;
            Contrast = Program.Manager.Contrast;
            Led = Program.Manager.Led;
            Volume = Program.Manager.Volume;
            Mic = Program.Manager.Microphone;
            Prox = Program.Manager.Proximity;
            Audio = Program.Manager.Audio;
        }

        public void OnPostSnapshot()
        {
            //Program.Connections.Send_cmd("im", 5);
        }
        public void OnPostStartRecording()
        {
            //Program.Connections.Send_cmd("ca", 1);
        }
        public void OnPostStopRecording()
        {
            //Program.Connections.Send_cmd("ca", 0);
        }




        public void OnPostSchedule(
            bool mondayCheck, int onTime1, int offTime1, int picVid1, int vLength1, int vDelay1, int sDelay1,
            bool teusdayCheck, int onTime2, int offTime2, int picVid2, int vLength2, int vDelay2, int sDelay2,
            bool WednesdayCheck, int onTime3, int offTime3, int picVid3, int vLength3, int vDelay3, int sDelay3,
            bool thursdayCheck, int onTime4, int offTime4, int picVid4, int vLength4, int vDelay4, int sDelay4,
            bool fridayCheck, int onTime5, int offTime5, int picVid5, int vLength5, int vDelay5, int sDelay5,
            bool saturdayCheck, int onTime6, int offTime6, int picVid6, int vLength6, int vDelay6, int sDelay6,
            bool sundayCheck, int onTime7, int offTime7, int picVid7, int vLength7, int vDelay7, int sDelay7)
        {
           
            if(mondayCheck == true)
            {               
                Program.Manager.updateSchedule(0, onTime1, offTime1, picVid1, vLength1, vDelay1, sDelay1);
            } 

            if(teusdayCheck == true)
            {                
                Program.Manager.updateSchedule(1, onTime2, offTime2, picVid2, vLength2, vDelay2, sDelay2);                
            }

            if(WednesdayCheck == true)
            {
                Program.Manager.updateSchedule(2, onTime3, offTime3, picVid3, vLength3, vDelay3, sDelay3);
            }

            if(thursdayCheck == true)
            {
                Program.Manager.updateSchedule(3, onTime4, offTime4, picVid4, vLength4, vDelay4, sDelay4);
            }

            if(fridayCheck == true)
            {
                Program.Manager.updateSchedule(4, onTime5, offTime5, picVid5, vLength5, vDelay5, sDelay5);
            }

            if(saturdayCheck == true)
            {
                Program.Manager.updateSchedule(5, onTime6, offTime6, picVid6, vLength6, vDelay6, sDelay6);
            }

            if(sundayCheck == true)
            {
                Program.Manager.updateSchedule(6, onTime7, offTime7, picVid7, vLength7, vDelay7, sDelay7);
            }                                    
        }// end onPostSchedule 

    }
}

ProjectGhost/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProjectGhost.Pages
{
	public class IndexModel : PageModel
	{
		public void OnGet()
		{

		}

        public void OnPostLogin(string email, string password)
        {
            Program.Manager.CheckID(email, password);
            if(Program.Manager.UserID != 0)
            {
                Response.Redirect("./admin");
            }
            else
            {
                Response.Redirect("./AddUser");
                // add error alert that email or password does not match
            }
            
        }
    }
}

ProjectGhost/Pages/AddUser.cshtml
@page
@model ProjectGhost.Pages.AddUserModel
@{
    ViewData["Title"] = "AddUser";

}


<div id="stars">
    <nav>
        <a href="./index" title="home">
            <img id="ghostLogo" src="~/images/ghostLogo.png" name="logo"/>
        </a>
        <span>Create Account</span>
    </nav>
    
    @if (Model.firstAttemptFail)
    {
        <div class="CreateAccountFields">
            <form method="post" asp-page-handler="CreateAccount">
                <div class="UserInfo">
                    <h4>User Information</h4>
                    <input type="email" name="email" placeholder="Email Address" required /><br />
                    <input type="password" name="password" placeholder="Password" required /><br />
                </div>
                <div class="GhostInfo">
                    <h4>Ghost Information</h4>
                    <input type="text" name="serialNum" placeholder="Serial Number" required /><br />
                    <span id="serialNumError">Serial number must match, AB12CD-AD Format </span><br />
                    <select name="ghostName" required>
                        <option>Your Ghost Name</option>
                        @foreach (var name in Model.GhostNames)
                        {
                            <option>@name</option>
                        }
                    </select><br />
                </div>
                <div class="CameraShedule">
                    <h4>Camera Schedule</h4>
                    **** not yet available ****<br />
                </div>
                    <input type="submit" value="Create Account" />
            </form>
        </div>
    }
    else
    {
        <div class="CreateAccountFields">
            <form id="CreateAccountForm" method="post" asp-page-handler="CreateAccount">
                <div class="UserInfo">
                    <span>User Information:</span><br />
                    <input type="email" name="email" placeholder="Email Address" required /><br />
                    <input type="password" name="password" placeholder="Password" required /><br />
                </div>
                <div class="GhostInfo">
                    <span>Ghost Information:</span><br />
                    <input type="text" name="serialNum" placeholder="Serial Number" required /><br />
                    <select name="ghostName" required>
                        <option>Your Ghost Name</option>
                        @foreach (var name in Model.GhostNames)
                        {
                            <option>@name</option>
                        }
                    </select><br />
                </div>
                <div class="CameraShedule">
                    <h4>Camera Schedule</h4>
                    **** not yet available ****<br />
                </div>

                <input type="submit" value="Create Account" />
            </form>

        </div>

    }

</div>

ProjectGhost/Pages/Index.cshtml
@page
@model IndexModel
@{
	ViewData["Title"] = "Home page";
}
<div id="stars">
    <nav>
        
        <a href="./index" title="home">
            <img id="ghostLogo" src="~/images/ghostLogo.png" name="logo" />
        </a>

        <form method="post" asp-page-handler="Login">
            <input type="email" name="email" value="" placeholder="email" required />
            <input type="password" name="password" value="" placeholder="password" required />
            <input type="submit" name="Login" value="Login" />
            <a href="./AddUser" title="Create Account">
                Create Account
            </a>
        </form>


    </nav>

	<div id="GhostBody">
		<img id="ghostRightBack" src="~/images/GhostSplit/rightBack.png" alt="Alternate Text" />
		<img id="ghostRightFront" onclick="goRight()" src="~/images/GhostSplit/rightFront.png" alt="Alternate Text" />
		<img id="ghostBottomBack" src="~/images/GhostSplit/bottomBack.png" alt="Alternate Text" />
		<img id="ghostCenter" onclick="goCenter()" src="~/images/GhostSplit/center.png" alt="Alternate Text" />
		<img id="ghostBottomFront" onclick="goDown()" src="~/images/GhostSplit/bottomFront.png" alt="Alternate Text" />
		<img id="ghostLeft" onclick="goLeft()" src="~/images/GhostSplit/left.png" alt="Alternate Text" />
		<img id="ghostTop" onclick="goUp()" src="~/images/GhostSplit/top.png" alt="Alternate Text" />
	</div>
</div>

ProjectGhost/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<title>@ViewData["Title"] - ProjectGhost</title>
	<environment>
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/css/site.css" />
	</environment>

</head>
<body>

	<partial name="_CookieConsentPartial" />

	<div class="stuff">
		@RenderBody()
	</div>
	<environment>
		<link rel="stylesheet" href="https://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
		<script src="~/js/starfield.js"></script>
	</environment>

	@RenderSection("Scripts", required: false)
</body>

</html>
<Footer>
	&copy; Masterfully Created by Devon Kassion, and Andrew Prior. 
</Footer>